apiVersion: v1
kind: Service
metadata:
  name: portfolio-svc
spec:
  selector:
    app: portfolio
    tier: backend
    release: production
  ports: 
  - protocol: TCP
    port: 80
    targetPort: portfolio-port
  type: ClusterIP