on:
  push:
    branches:
      - feature/k8s

jobs:
  # audit_lint_test:
  #   name: audit_lint_test
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-node@v2
  #     with:
  #       node-version: '14'
  #   - name: Install dependencies
  #     run: |
  #       npm i
  #   - name: Run audit
  #     run: |
  #       npm audit
  #   - name: Run linter
  #     run: |
  #       npm run lint
  #   - name: Run build
  #     run: |
  #       npm run build
  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout master
      uses: actions/checkout@master

    - run: |
        docker build \
          -t portfolio .
        docker tag portfolio registry.digitalocean.com/awelsh/portfolio:${{ github.sha }}

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 600

    - name: Push image to DigitalOcean Container Registry
      run: docker push registry.digitalocean.com/awelsh/portfolio:${{ github.sha }}

    - name: Installing gettext to access envsubst to replace values.
      run: sudo apt-get install gettext

    - name: Replace GH SHA variable with SHA value.
      run: envsubst < $GITHUB_WORKSPACE/deployments/deployment/production.yml > $GITHUB_WORKSPACE/deployments/deployment/patched_portfolio.yml

    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 actions-example-k8s-1-18

    - name: Deploy to DigitalOcean Kubernetes
      run: kubectl apply -f $GITHUB_WORKSPACE/deployments/deployment/patched_portfolio.yml

    - name: Verify deployment
      run: kubectl rollout status deployment/static-example
