# Flow to audit, lint and test each commit, but not to master.
# Master CI will be within the CD flow.
on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!master'
env:
  NODE_VERSION: '14'
jobs:
  audit_lint_build:
    name: Audit, lint and TSC build.
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install dependencies
      run: |
        npm i
    - name: Run audit
      run: |
        npm audit
    - name: Run linter
      run: |
        npm run lint
    - name: Run build
      run: |
        npm run build
